### ISSUE TITLE
Running it

### ISSUE THREAD

**Issue by PocketKiller** [ImagicalCorp/MCPETransfer#1]
How can i run and use it? i read the README

**Comment by robske110** [comment]
Then it's running...

**Comment by robske110** [comment]
After you typed java -jar ...

**Comment by PocketKiller** [comment]
?

**Comment by robske110** [comment]
Send a screenshot of your terminal

**Comment by vvzar** [comment]
Please explain, how can i use it, for teleporting players from one server to another?

**Comment by robske110** [comment]
It is not working yet

**Comment by keithkfng** [comment]
Updated to latest version. I'll need to see how to actually use it to transfer players.

**Comment by Driesboy** [comment]
dont work

**Comment by robske110** [comment]
Of course this doesnt work yett
