### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Driesboy** [ImagicalCorp/MCPETransfer#2]
Searching for BouncyBall jar...
Could not find BouncyBall-1.0-SNAPSHOT.jar, perhaps it does not exist?
logout

**Comment by vvzar** [comment]
change string in start.sh like this:

if [ -f ./BouncyBall.jar ]; then
        BOUNCY="./BouncyBall.jar"
        echo "Found BouncyBall jar."
and rename BouncyBall-1.0-SNAPSHOT.jar to BouncyBall.jar 

start.sh have to be placed in same directory

**Comment by keithkfng** [comment]
Have you even compiled it? No.
