### ISSUE TITLE
Proxy takes client port and trying to create socket with it!

### ISSUE THREAD

**Issue by vvzar** [ImagicalCorp/MCPETransfer#3]
But different clients can use same port like 19132 and different ip.
So we can see this:

[18:00:33] [RemoteServer-/x.x.x.x:19132/ERROR] [BouncyBall]: SocketException: Address already in use
java.net.BindException: Address already in use
        at java.net.PlainDatagramSocketImpl.bind0(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:94)
        at java.net.DatagramSocket.bind(DatagramSocket.java:392)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:299)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:271)
        at net.beaconpe.bouncyball.session.RemoteServerSession.run(RemoteServerSession.java:51)

**Comment by keithkfng** [comment]
Change it in the config file.

**Comment by vvzar** [comment]
Just read Once again. My port for remote server is complete different

**Comment by vvzar** [comment]
It is log messages appear when some clients trying to connect to my server (proxy)

**Comment by keithkfng** [comment]
No. It's 19132 and you said it's the same...
Otherwise I don't get what you're trying to say.

**Comment by vvzar** [comment]
Look at this:

public void run(){
        setName("RemoteServer-"+clientAddr.toString());
        try {
            int port = Integer.parseInt(clientAddr.toString().split(":")[1]);
            socket = new DatagramSocket(port);
            server.getLogger().debug("Opened connection to "+serverAddress.toString());
            while (running && (!isInterrupted())) {
                if(timeoutTimes >= 5){
                    break;
                }
                socket.setSoTimeout(2000);

                byte[] recvBuf = new byte[1024 * 1024];
                DatagramPacket dp = new DatagramPacket(recvBuf, recvBuf.length);
                try {
                    socket.receive(dp);
                    dp.setData(Arrays.copyOf(recvBuf, dp.getLength()));
                    handlePacket(dp.getData());
                } catch (SocketTimeoutException e) {
                    timeoutTimes++;
                } catch (IOException e) {
                    server.getLogger().error("IOException: " + e.getMessage());
                    e.printStackTrace();
                }
            }
            server.getLogger().debug("Closed connection to "+serverAddress.toString());
        } catch(SocketException e) {
            server.getLogger().error("SocketException: "+e.getMessage());
            e.printStackTrace();
        }
    }

As You can see, this code takes address and port of client and then, proxy trying to open socket with this  variable
Just add check to open socket part if port is busy,  $port = $port + 1

**Comment by keithkfng** [comment]
Wait how did you even get it to work?
