### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalCorp/MCPETransfer#5]
Whats a proxy server, does this have the same stuff as ImgaicalMine?

**Comment by InfornoFire** [comment]
Also, how is it used, i dont get it. Is it like a sevrer hub to teleport to servers

**Comment by InfornoFire** [comment]
Is this like a server hub to teleport to servers?

**Comment by InfornoFire** [comment]
Is it like a server hub, or does it transfer you to another proxy server

**Comment by keithkfng** [comment]
It'll soon enable transferring from server to server. I'll make a Gitter chat and a Travis project now.
